language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

services:
- postgresql

before_script:
 - psql -c 'create database afwadsa;' -U postgres

script: 
  - npm test
  - npm run coveralls
